name: Deploy to Koyeb

on:
  workflow_run: 
    workflows: ["Sonarcloud", "Codecov"]
    types:
      - completed
    branches:
      - main
      - staging

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
  KOYEB_APP_NAME: abundant-ardis
  KOYEB_SERVICE_NAME: a10-buildingstore

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}
    
    - name: Install and configure the Koyeb CLI
      uses: koyeb-community/koyeb-actions@v2
      with:
        api_token: ${{ secrets.KOYEB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to Koyeb
      run: koyeb service redeploy ${{ env.KOYEB_APP_NAME }}/${{ env.KOYEB_SERVICE_NAME }}